[package]
name = "bitwarden-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
cli-clipboard = "0.4.0"
cursive = "0.20.0"
rand = "0.8.5"
ratatui = "0.27.0"
rust-argon2 = "2.1.0"
simple_crypt = "0.2.3"
zeroize = "1.8.1"
